// =================================================================
// Azure OpenAI Provider - Enterprise対応の最新実装
// 2025年最新API対応 (2025-04-01-preview)
// =================================================================

import { 
  AIProvider,
  AIProviderType,
  AIProviderConfig,
  TextGenerationRequest,
  ImageGenerationRequest,
  VideoAnalysisRequest,
  AIProviderError,
  AIProviderConnectionError,
  AIProviderConfigError,
  AIProviderRateLimitError,
  AIProviderQuotaExceededError
} from './aiProviderInterface';

import { getAvailableModels } from './modelRegistry';

// Azure OpenAI SDK (注意: 実際のプロジェクトでは適切なSDKをインストール)
interface AzureOpenAIClient {
  chat: {
    completions: {
      create: (params: any) => Promise<any>;
    };
  };
  images: {
    generate: (params: any) => Promise<any>;
  };
}

export class AzureOpenAIProvider implements AIProvider {
  name: AIProviderType = 'azure';
  private client: AzureOpenAIClient;
  private config: AIProviderConfig;
  private baseURL: string;

  constructor(config: AIProviderConfig) {
    this.config = config;

    if (!config.apiKey) {
      throw new AIProviderConfigError(
        'Azure OpenAI API key is required',
        'azure'
      );
    }

    if (!config.endpoint) {
      throw new AIProviderConfigError(
        'Azure OpenAI endpoint is required',
        'azure'
      );
    }

    this.baseURL = `${config.endpoint}/openai/deployments`;

    try {
      // 注意: 実際の実装では適切なAzure OpenAI SDKを使用
      this.client = this.createAzureClient(config);
    } catch (error) {
      throw new AIProviderConnectionError(
        `Failed to initialize Azure OpenAI client: ${error.message}`,
        'azure',
        error as Error
      );
    }
  }

  async generateText(request: TextGenerationRequest): Promise<string> {
    try {
      const deploymentName = this.getDeploymentName('textGeneration', request.model);
      
      const response = await this.client.chat.completions.create({
        model: deploymentName,
        messages: [
          ...(request.systemPrompt ? [{ role: 'system', content: request.systemPrompt }] : []),
          { role: 'user', content: request.prompt }
        ],
        temperature: request.temperature || 0.7,
        max_tokens: request.maxTokens || 4096,
        top_p: 1,
        frequency_penalty: 0,
        presence_penalty: 0,
      });

      if (!response.choices || response.choices.length === 0) {
        throw new AIProviderError(
          'No response generated by Azure OpenAI',
          'azure'
        );
      }

      return response.choices[0].message.content || '';
    } catch (error) {
      throw this.handleAzureError(error, 'Text Generation');
    }
  }

  async generateImage(request: ImageGenerationRequest): Promise<string> {
    try {
      const deploymentName = this.getDeploymentName('imageGeneration', request.model);
      
      const response = await this.client.images.generate({
        model: deploymentName,
        prompt: request.prompt,
        size: request.size || '1024x1024',
        quality: request.quality || 'standard',
        style: request.style || 'natural',
        n: request.n || 1,
        response_format: 'b64_json'
      });

      if (!response.data || response.data.length === 0) {
        throw new AIProviderError(
          'No image generated by Azure OpenAI',
          'azure'
        );
      }

      const b64Data = response.data[0].b64_json;
      return `data:image/png;base64,${b64Data}`;
    } catch (error) {
      throw this.handleAzureError(error, 'Image Generation');
    }
  }

  async analyzeVideo(request: VideoAnalysisRequest): Promise<string> {
    try {
      const deploymentName = this.getDeploymentName('videoAnalysis', request.model);
      
      // GPT-4o Vision を使用してビデオフレーム分析
      const response = await this.client.chat.completions.create({
        model: deploymentName,
        messages: [{
          role: 'user',
          content: [
            { type: 'text', text: request.prompt },
            { 
              type: 'image_url', 
              image_url: { 
                url: request.videoData,
                detail: 'high'
              } 
            }
          ]
        }],
        temperature: 0.3,
        max_tokens: 4096,
      });

      if (!response.choices || response.choices.length === 0) {
        throw new AIProviderError(
          'No analysis generated by Azure OpenAI',
          'azure'
        );
      }

      return response.choices[0].message.content || '';
    } catch (error) {
      throw this.handleAzureError(error, 'Video Analysis');
    }
  }

  async validateConfig(config: AIProviderConfig): Promise<boolean> {
    try {
      if (!config.apiKey || !config.endpoint) {
        return false;
      }

      // 軽量なテストリクエストで設定を検証
      const testClient = this.createAzureClient(config);
      const testDeployment = config.deployments?.textGeneration || 'gpt-4o';
      
      await testClient.chat.completions.create({
        model: testDeployment,
        messages: [{ role: 'user', content: 'test' }],
        max_tokens: 1
      });

      return true;
    } catch (error) {
      return false;
    }
  }

  async getAvailableModels(): Promise<{ [key: string]: string[] }> {
    try {
      const textModels = getAvailableModels('azure', 'text').map(m => m.id);
      const imageModels = getAvailableModels('azure', 'image').map(m => m.id);
      const videoModels = getAvailableModels('azure', 'video').map(m => m.id);

      return {
        textGeneration: textModels,
        imageGeneration: imageModels,
        videoAnalysis: videoModels,
      };
    } catch (error) {
      return {
        textGeneration: [],
        imageGeneration: [],
        videoAnalysis: [],
      };
    }
  }

  async estimateCost(request: any): Promise<number> {
    // Azure OpenAI 価格計算 (2025年価格)
    const pricing = {
      'gpt-4.1': { input: 0.075, output: 0.15 },
      'gpt-4o': { input: 0.05, output: 0.10 },
      'o3-mini': { input: 0.011, output: 0.044 },
      'gpt-4-turbo': { input: 0.01, output: 0.03 },
      'gpt-image-1': { image: 0.08 },
      'dall-e-3': { image: 0.04 },
    };

    const modelId = request.model || 'gpt-4o';
    const modelPricing = pricing[modelId];
    
    if (!modelPricing) {
      return 0.01; // Default small cost
    }

    if (request.task === 'text') {
      const inputTokens = Math.ceil((request.prompt?.length || 100) / 4);
      const outputTokens = request.maxTokens || 1000;
      return (inputTokens * modelPricing.input + outputTokens * modelPricing.output) / 1000000;
    } else if (request.task === 'image') {
      return modelPricing.image || 0.04;
    }

    return 0.01;
  }

  // Azure OpenAI クライアント作成
  private createAzureClient(config: AIProviderConfig): AzureOpenAIClient {
    // 注意: 実際の実装では適切なAzure OpenAI SDKを使用
    // 以下は型安全性のためのモック実装
    return {
      chat: {
        completions: {
          create: async (params: any) => {
            // 実際のAzure OpenAI API呼び出しをここで実装
            const url = `${this.baseURL}/${params.model}/chat/completions?api-version=2025-04-01-preview`;
            
            const response = await fetch(url, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'api-key': config.apiKey
              },
              body: JSON.stringify(params)
            });

            if (!response.ok) {
              throw new Error(`Azure OpenAI API error: ${response.status} ${response.statusText}`);
            }

            return await response.json();
          }
        }
      },
      images: {
        generate: async (params: any) => {
          // 実際のAzure OpenAI Image API呼び出しをここで実装
          const url = `${this.baseURL}/${params.model}/images/generations?api-version=2025-04-01-preview`;
          
          const response = await fetch(url, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'api-key': config.apiKey
            },
            body: JSON.stringify(params)
          });

          if (!response.ok) {
            throw new Error(`Azure OpenAI Image API error: ${response.status} ${response.statusText}`);
          }

          return await response.json();
        }
      }
    };
  }

  // デプロイメント名取得
  private getDeploymentName(taskType: string, modelId?: string): string {
    if (modelId && this.config.deployments?.[taskType]) {
      return this.config.deployments[taskType];
    }

    // デフォルトデプロイメント名
    const defaults = {
      textGeneration: 'gpt-4o',
      imageGeneration: 'dall-e-3',
      videoAnalysis: 'gpt-4o'
    };

    return this.config.deployments?.[taskType] || defaults[taskType] || 'gpt-4o';
  }

  // Azure固有エラーハンドリング
  private handleAzureError(error: unknown, context: string): AIProviderError {
    if (error instanceof AIProviderError) {
      return error;
    }

    if (error instanceof Error) {
      const message = error.message.toLowerCase();
      
      if (message.includes('unauthorized') || message.includes('401')) {
        return new AIProviderConfigError(
          'Invalid Azure OpenAI API key or endpoint configuration',
          'azure',
          error
        );
      }
      
      if (message.includes('quota') || message.includes('429')) {
        return new AIProviderQuotaExceededError(
          'Azure OpenAI quota exceeded. Please check your usage limits.',
          'azure',
          error
        );
      }
      
      if (message.includes('rate limit')) {
        return new AIProviderRateLimitError(
          'Azure OpenAI rate limit exceeded. Please try again later.',
          'azure',
          error
        );
      }
      
      if (message.includes('deployment')) {
        return new AIProviderConfigError(
          'Azure OpenAI deployment configuration error. Please check your deployment names.',
          'azure',
          error
        );
      }
      
      return new AIProviderError(
        `Azure OpenAI ${context} error: ${error.message}`,
        'azure',
        'UNKNOWN_ERROR',
        error
      );
    }

    return new AIProviderError(
      `Azure OpenAI ${context}: Unknown error occurred`,
      'azure',
      'UNKNOWN_ERROR'
    );
  }
}